- name: install mariadb package (ubuntu)
  tags: mariadb-server
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: install mariadb package (CentOS)
  tags: centos,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"
